### ISSUE TITLE
Widget should show currently running events

### ISSUE THREAD

**Issue by rain-bipper** [GreatApo/Amazfit-Timeline-Widget#2]
If event was started before current time, but ends after - it should be shown in timeline widget. This is usable for long term events, such as meetings or birthdays.

**Comment by rain-bipper** [comment]
I'll also make patch to AmazMod, to correctly use "all day" types of events.

**Comment by GreatApo** [comment]
@rain-bipper I am not sure if this also needs to be implemented in Amazmod (if current event is forwarded). I have seen that the "All day" events do not show up properly, if you have the fix almost ready, it would be awesome!


FYI, there are some small code changes in Calendar (Timeline code) that are not implemented here.

**Comment by rain-bipper** [comment]
> I have seen that the "All day" events do not show up properly, if you have the fix almost ready, it would be awesome!

I already made some research and have an idea how to fix this. I'll make an Issue in AmazMod repo and start discussion there.

> FYI, there are some small code changes in Calendar (Timeline code) that are not implemented here.

I don't quite understand what kind of change you're talking about, can you elaborate?

**Comment by GreatApo** [comment]
> I don't quite understand what kind of change you're talking about, can you elaborate?

[These changes](https://github.com/GreatApo/AmazfitPaceCalendarWidget/commit/5b580bfbba0732fd5066c2b93ec5d757c933317b), nothing really serious. If you are going to make a pull request, I will implement them afterwards :)

**Comment by rain-bipper** [comment]
Ok, I've got it.

And oh - there is already support of "all day" in widget. Not perfect, IMHO, but still.. :)
So I'll try to make necessary changes only here, avoiding to patch AmazMod.

I write couple of words about temporary zones and "all day" events here.
We have as many as 4 zones:
1. calendar time zone
2. event time zone
3. phone time zone
4. watch time zone

In my opinion, it would be ideal to send all timestamps to the watch in UTC, with a flag in which time zone to display them on the watch (calendar time zone, or phone time zone, for example). But this would require changing the communication protocol and updating AmazMod definitely will have to update and Service in same time.
So I came up with the idea of sending a local phone midnight time from phone for "all day" events.

Now AmazMod definitely has the error in the calculation of the offset. I have "all day" events displayed as starting at 6:00 am, although they have a timestamp of 00:00 UTC (my timezone is +3:00).

**Comment by GreatApo** [comment]
Yes there is a code that tries to identify the all day events but currently it fails :P

The phone and watch are supposed to be synced in terms of time. From my recent GreatFit experience, it is very easy to find the timezone directly on watch.

I think the only change that needs to be made is to evaluate whether the time difference of the start/end is 24h. That will probably solve most problems because I also get some All Day events for UTC+4 and get the starting time at 4 AM.

**Comment by rain-bipper** [comment]
Here's what I suggest:
1. add the "all_day" parameter to the data sent from the phone (this will not break the current protocol, I checked)
2. send local midnight (for begin) and local midnight + 1 day (for end) as timestamps for the "all_day" event
3. on the widget side, we process timestamps as usual, and for events marked with "all_day" flag we display "All day".

**Comment by rain-bipper** [comment]
> 2. send local midnight (for begin) and local midnight + 1 day (for end) as timestamps for the "all_day" event

Local midnight of date of the event of course.

**Comment by rain-bipper** [comment]
um.. I just found out, that system calendar returns all timestamps in UTC format, regardless of TZ flags. These TZ flags are only hints how to display these timestamps. So, since we just want to display in local time, there is no need to do any offset correction.

For me "all_day" event is shown as 03:00 - and that is correct, google calendar web site shows me this event as "GMT+03".

So in in the second paragraph I suggest to do nothing and send timestamps as is, without any correction.

I'll make PR to AmazMod, to show what I mean :)

**Comment by rain-bipper** [comment]
I've noticed, that "description" and "account" fields of calendar data are not used.

**Comment by rain-bipper** [comment]
> These changes, nothing really serious. If you are going to make a pull request, I will implement them afterwards :)

As far as I understood, AmazfitPaceCalendarWidget contains only Calendar widget. 
Don't you want to move the Timeline _widget_ there too and mark the current repository as deprecated? I think one application can contain as many widgets as it wants

**Comment by fcaronte** [comment]
the perfect thing will be to have only one app with timeline and calendar but were i can choose what i want to see as widget, if you know how to do, i hope to see soon.

**Comment by rain-bipper** [comment]
>  but were i can choose what i want to see as widget, if you know how to do, i hope to see soon

AmazMod settings/Reorder Widgets - here you can enable/disable any widget. Or I miss something?

**Comment by fcaronte** [comment]
yes you need to install both two, and pace calendar have a timeline too need some link from timeline apk to open pace calendar apk, because as now will be two separated app ( i install your version and confirm "allday" show correctly for today too. good job)

**Comment by rain-bipper** [comment]
My point is to make single apk with both widgets in it - Calendar and Timeline. This will be conveniently to use and saves some resources of watch

**Comment by fcaronte** [comment]
Yes if can work is the best way, and add an icon on timeline to open calendar as we just do now with calendar
![IMG_20190915_132738](https://user-images.githubusercontent.com/26366403/65028634-a752d700-d93c-11e9-86fe-d97006613d13.jpg)
